### PR TITLE
Allow additional arguments to be passed to cloc

### PR DESCRIPTION
**Pull request by JHartzer**
This PR would allow additional arguments to be passed to cloc using the `options` argument. In a workflow, this might look like:
```yaml
      - name: Count Lines of Code
        uses: djdefi/cloc-action@5.1
        with:
          options: --exclude-lang=HTML --md --report-file=cloc.md
```

I modified the ENTRYPOINT to allow the optional arguments to be passed to the shell script. I am not familiar with `dumb-init` so I hope this was the correct way to extend the entrypoint.

### CODE REVIEW

**Review by JHartzer — COMMENTED** [review]
Thank you for the addition!

**Comment by JHartzer** [comment]
Is there any additional testing or work that you would like to see done before this could get merged in?

**Comment by JHartzer** [comment]
Is there any additional testing or work that you would like to see done before this could get merged in?

**Comment by JHartzer** [comment]
Is there any additional work or testing you would like to see before merging?

**Comment by djdefi** [comment]
It doesn't seem to be working as expected based on https://github.com/djdefi/cloc-action/actions/runs/6265243101/job/17013644796#step:5:1 so it needs a bit more tweaking I think to get working fully.

**Comment by djdefi** [comment]
Actually that may be due to the Action itself running on `main` note being updated...

**Pull request merged**
